// PSYCHOLOGIST

// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
// END

// PATIENT
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const FETCH_PATIENTS = 'FETCH_PATIENTS';

export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAIL = 'CREATE_PATIENT_FAIL';

export const CREATE_PATIENT_CODE_SUCCESS = 'CREATE_PATIENT_CODE_SUCCESS';
export const CREATE_PATIENT_CODE_FAIL = 'CREATE_PATIENT_CODE_FAIL';

export const EDIT_PATIENT_SUCCESS = 'EDIT_PATIENT_SUCCESS';
export const EDIT_PATIENT_FAIL = 'EDIT_PATIENT_FAIL';
// END

// CONSULT
export const FETCH_CONSULT = 'FETCH_CONSULT';
export const FETCH_CONSULTS = 'FETCH_CONSULTS';

export const CREATE_CONSULT_SUCCESS = 'CREATE_CONSULT_SUCCESS';
export const CREATE_CONSULT_FAIL = 'CREATE_CONSULT_FAIL';
// END

// EXERCISE
export const CREATE_EXERCISE_ALL_SUCCESS = 'CREATE_EXERCISE_ALL_SUCCESS';
export const CREATE_EXERCISE_ALL_FAIL = 'CREATE_EXERCUSE_ALL_FAIL';

export const CREATE_EXERCISE_ONE_SUCCESS = 'CREATE_EXERCISE_ONE_SUCCESS';
export const CREATE_EXERCISE_ONE_FAIL = 'CREATE_EXERCISE_ONE_FAIL';
// END

// QUESTION
export const CREATE_QUESTION_ALL_SUCCESS = 'CREATE_QUESTION_ALL_SUCCESS';
export const CREATE_QUESTION_ALL_FAIL = 'CREATE_EXERCUSE_ALL_FAIL';

export const CREATE_QUESTION_ONE_SUCCESS = 'CREATE_QUESTION_ONE_SUCCESS';
export const CREATE_QUESTION_ONE_FAIL = 'CREATE_QUESTION_ONE_FAIL';
// END

// END PSYCHOLOGIST

// PATIENT

// AUTH PATIENT
export const LOGIN_PATIENT_SUCCESS = 'LOGIN_PATIENT_SUCCESS';
export const LOGIN_PATIENT_FAIL = 'LOGIN_PATIENT_FAIL';

export const FETCH_PATIENT_PATIENT = 'FETCH_PATIENT_PATIENT';
export const FETCH_PATIENT_PSYCHOLGIST = 'FETCH_PATIENT_PSYCHOLOGIST';

export const SET_PATIENT_LAST_ACCESS = 'SET_PATIENT_LAST_ACCESS';

export const SET_DIARY = 'SET_DIARY';

export const FETCH_DIARY = 'FETCH_DIARY';
// END

// END PATIENT
