// BEGIN AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
// END AUTH

// BEGIN PACIENTE
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const FETCH_PATIENTS = 'FETCH_PATIENTS';

export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAIL = 'CREATE_PATIENT_FAIL';

export const EDIT_PATIENT_SUCCESS = 'EDIT_PATIENT_SUCCESS';
export const EDIT_PATIENT_FAIL = 'EDIT_PATIENT_FAIL';
// END PACIENTE

// BEGIN CONSULT
export const FETCH_CONSULT = 'FETCH_CONSULT';
export const FETCH_CONSULTS = 'FETCH_CONSULTS';

export const CREATE_CONSULT_SUCCESS = 'CREATE_CONSULT_SUCCESS';
export const CREATE_CONSULT_FAIL = 'CREATE_CONSULT_FAIL';
// END CONSULT

// BEGIN EXERCISE
export const CREATE_EXERCISE_ALL_SUCCESS = 'CREATE_EXERCISE_ALL_SUCCESS';
export const CREATE_EXERCISE_ALL_FAIL = 'CREATE_EXERCUSE_ALL_FAIL';

export const CREATE_EXERCISE_ONE_SUCCESS = 'CREATE_EXERCISE_ONE_SUCCESS';
export const CREATE_EXERCISE_ONE_FAIL = 'CREATE_EXERCISE_ONE_FAIL';
// END EXERCISE
